### ISSUE TITLE
A4 paper is not 8.5" wide

### ISSUE THREAD

**Issue by scottmcm** [lf94/blots#1]
https://github.com/lf94/blots/blob/master/src/main.rs#L20:
```rust
const A4_WIDTH_INCHES:f32 = 8.5;
```

A4 paper is 8.19"‒8.34" wide.

**Comment by lf94** [comment]
Where are you sourcing this information?

**Comment by scottmcm** [comment]
Wikipedia <https://en.wikipedia.org/wiki/ISO_216#Dimensions_of_A,_B_and_C_Series>, or any number of other sites.  8.3" is the rounded number; the range I gave includes the ±2mm tolerance.

If you want a more authoritative source, it looks like Malaysia has a copy of ISO 216 on their website: http://stg.jsm.gov.my/documents/372014/372056/MS+ISO+2162008+WRITING+PAPER+AND+CERTAIN+CLASSES+OF+PRINTED+MATTER+-+TRIMMED+SIZES+-+A+AND+B+SERIES,%20AND+INDICATION-869377.pdf/83e24fdb-ab71-45aa-af8e-fb4a14909416?version=1.0&previewFileIndex=

**Comment by lf94** [comment]
Perfect. I will change it to reflect this :smile: Thank you @scottmcm !
